### ISSUE TITLE
it takes time to open HTML documents in AMP format

### ISSUE THREAD

**Issue by agutierrez25249** [Simon-Laux/ZHV#26]
it takes time to open HTML documents in AMP format

This format is designed to open faster on android however ZHV takes a long time to open.

example

http://www.cubadebate.cu/noticias/2021/05/01/concluye-fase-iii-del-ensayo-clinico-del-candidato-vacunal-abdala-en-granma-santiago-de-cuba-y-guantanamo/amp/

**Comment by Simon-Laux** [comment]
amp is not a format it's a js framework by google, which needs to download external js from google servers to function.
I'd be surprised if it works at all, because:

> It doesn't allow loading resources from the web. Assets must be inline because it only loads from the index html file for now.
> ~ the readme of this repo

**Comment by Simon-Laux** [comment]
Not sure how we can solve this, maybe ask @adbenitez to add some transformation to amp pages so they don't require external scripts anymore.
Or implementing that additional resources can be loaded from the zip and bundle more stuff into the zip.
Or including popular js libraries into the apk (this makes the apk substantially bigger, though,

**Comment by agutierrez25249** [comment]
I like the second idea  
> Or implementing that additional resources can be loaded from the zip and bundle more stuff into the zip.
