### ISSUE TITLE
[FR] Implement markdown reader?

### ISSUE THREAD

**Issue by Simon-Laux** [Simon-Laux/ZHV#6]
To open/render markdown files. Maybe add a button to change appearance (font, font size and bg color)

As we have no way to include media other than base64 data uri's we could add a `.md.zip` / `.zmd` format that includes media (this can be used for ziped htmls too).

**Comment by adbenitez** [comment]
this could be of use, the bot already generates markdown files

**Comment by Simon-Laux** [comment]
I work on it, though you'll have to convert the links to mailto links in simplebot before sending the markdown file
