### ISSUE TITLE
Open via file scheme is broken

### ISSUE THREAD

**Issue by Simon-Laux** [Simon-Laux/ZHV#8]

**Comment by Simon-Laux** [comment]
seems to be resolved now

**Comment by adbenitez** [comment]
don't work for me, I had jtested with:
https://github.com/Simon-Laux/ZHV/releases/download/1.3/zhv.apk
is the right apk?? I recommend to use the same tag as in github for the version inside the app, it says version 4, I don't know if that is this 1.3 release

**Comment by Simon-Laux** [comment]
I still need to upload the version with the version code 5 to github.
